$(document).ready(function(){
    $('#btnIllust').click(function(){
        $(this).addClass('active');
        $('#btnTranslate').removeClass('active');
        $('#btnVrd3D').removeClass('active');
        $('#btnOther').removeClass('active');
        $('#Illust').fadeIn();
        $('#Translate').fadeOut();
        $('#Vrd3d').fadeOut();
        $('#GraphicDesign').fadeOut();
    })
    $('#btnTranslate').click(function(){
        $(this).addClass('active');
        $('#btnIllust').removeClass('active');
        $('#btnVrd3D').removeClass('active');
        $('#btnGraphicDesign').removeClass('active');
        $('#Illust').fadeOut();
        $('#Translate').fadeIn();
        $('#Vrd3d').fadeOut();
        $('#GraphicDesign').fadeOut();
    })
    $('#btnVrd3D').click(function(){
        $(this).addClass('active');
        $('#btnIllust').removeClass('active');
        $('#btnTranslate').removeClass('active');
        $('#btnOther').removeClass('active');
        $('#Illust').fadeOut();
        $('#Translate').fadeOut();
        $('#Vrd3d').fadeIn();
        $('#GraphicDesign').fadeOut();
    })
    $('#btnOther').click(function(){
        $(this).addClass('active');
        $('#btnIllust').removeClass('active');
        $('#btnTranslate').removeClass('active');
        $('#btnVrd3D').removeClass('active');
        $('#Illust').fadeOut();
        $('#Translate').fadeOut();
        $('#Vrd3d').fadeOut();
        $('#GraphicDesign').fadeIn();
    })

})